from enum import Enum

class State(Enum):
    INIT = "INIT"
    COLLECT_PROFILE = "COLLECT_PROFILE"
    RETRIEVE_SCHEMES = "RETRIEVE_SCHEMES"
    CHECK_ELIGIBILITY = "CHECK_ELIGIBILITY"
    RESOLVE_GAPS = "RESOLVE_GAPS"
    SELECT_SCHEME = "SELECT_SCHEME"
    APPLY = "APPLY"
    CONFIRMATION = "CONFIRMATION"
    END = "END"
